esphome:
  name: bad
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BME280-Bad"
    password: !secret captive_portal_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_psk

ota:
  password: !secret ota_password

i2c:
  sda: GPIO4 #D2
  scl: GPIO5 #D1
  scan: True
  frequency: 10kHz
  id: bus_a
  
# https://lastminuteengineers.com/bme280-arduino-tutorial/
sensor:
  - platform: bme280
    temperature:
      name: "Bad Temperature"
      oversampling: 16x
    pressure:
      name: "Bad Pressure"
    humidity:
      name: "Bad Humidity"
    address: 0x76
    update_interval: 60s
