esphome:
  name: heizung
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heizung"
    password: !secret captive_portal_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_psk

ota:
 - platform: esphome
   password: !secret ota_password

dallas:
  - pin: D4

sensor:
  - platform: uptime
    name: "Heizung Uptime"
  - platform: wifi_signal
    name: "Heizung WiFi Signal"
  #- platform: template
  #  name: "Heizung Free Memory"
  #  lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
  #  unit_of_measurement: 'kB'
  #  state_class: measurement
  - platform: dallas
    address: 0xca0722b159b6e828
    name: "VL"
  - platform: dallas
    address: 0x990822b15bd09828
    name: "Boiler"
  - platform: dallas
    address: 0xf90822b16fde1a28
    name: "RL"
  - platform: dallas
    address: 0x010822b16508b628
    name: "Zirkulation"
  - platform: dallas
    address: 0x1b0822b161e83928
    name: "WW VL"
  - platform: dallas
    address: 0xee0722b154f9a528
    name: "WW RL"
    
